[package]
name = "httpclient"
version = "0.1.10"
edition = "2021"
description = "HTTP client with middleware. Middleware provides composable support for record/replay, logging, exponential backoff, and more."
license = "MIT"

[dependencies]
async-trait = "0.1.52"
encoding_rs = "0.8.30"
futures = "0.3.21"
http = "0.2.6"
hyper = { version = "0.14.17", features = ["server"] }
hyper-rustls = "0.23.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
urlencoding = "2.1.0"
walkdir = "2.3.2"
